### ISSUE TITLE
How to get the seed words for specific aspect on SPACE dataset?

### ISSUE THREAD

**Issue by jeewoo1025** [brcsomnath/SemAE#3]
Hello. Dear, Author.
Thank you for such awesome contributions!

I am analyzing the code of SemAE, and I found out that seeds play an important role during aspect-specific inference.
(It's a lot more than the seeds provided by [QT](https://github.com/stangelid/qt))
I really want to know how the seeds are generated, but I couldn't find that code. 😥
Please could you upload the code for making the seeds?

Thank in advance.

**Comment by brcsomnath** [comment]
Sorry for the delay in replying.

We do not generate seed words on our own. We use the seed words provided with the original dataset [here](https://github.com/stangelid/qt/tree/main/data/seeds).  Please reach out to the authors of QT for details about the seed word generation process.
